apiVersion: apps/v1
kind: Deployment # Kubernetes resource type
metadata:
  name: livescorei-deployment
spec:
  selector:
    matchLabels:
      app: livescorei
  replicas: 2 # Number of replicas
  template:
    metadata:
      labels:
        app: livescorei
    spec:
      containers:
        - name: livescorei
          image: jeevanvpatel/livescorei # Image in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource type
metadata: 
  name: livescoreissvc
spec:
  selector:
    app: livescorei
  ports:
    - protocol: "TCP"
      port: 8080 # The port  in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.